# Generated by Django 3.1 on 2020-10-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_institucion', '0003_auto_20201016_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
